// Supabase Database Types
// This file is auto-generated. Do not edit manually.
// Run `npm run supabase:gen-types` to regenerate.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be auto-generated by Supabase CLI
    }
    Views: {
      // Views will be auto-generated by Supabase CLI
    }
    Functions: {
      // Functions will be auto-generated by Supabase CLI
    }
    Enums: {
      // Enums will be auto-generated by Supabase CLI
    }
    CompositeTypes: {
      // Composite types will be auto-generated by Supabase CLI
    }
  }
}

// Placeholder types - these will be replaced when Supabase types are generated
export type Tables<T extends keyof Database['public']['Tables']> = 
  Database['public']['Tables'][T]
export type Enums<T extends keyof Database['public']['Enums']> = 
  Database['public']['Enums'][T]
