name: LifeOS CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # ==================================================
  # Code Quality & Build Check
  # ==================================================
  build-and-lint:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: TypeScript type checking
        run: npx tsc --noEmit
      
      - name: ESLint check (if exists)
        run: |
          if [ -f ".eslintrc.json" ] || [ -f ".eslintrc.js" ] || [ -f "eslint.config.js" ]; then
            npx eslint . --ext .ts,.tsx,.js,.jsx --max-warnings 0 || echo "ESLint completed with warnings"
          else
            echo "No ESLint config found, skipping"
          fi
        continue-on-error: true
      
      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      
      - name: Check build output
        run: |
          echo "✅ Build completed successfully"
          ls -la .next/ || echo "No .next directory found"

  # ==================================================
  # Basic Testing
  # ==================================================
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests (if exists)
        run: |
          if grep -q '"test"' package.json; then
            npm test
          else
            echo "No test script found in package.json, skipping tests"
          fi
        continue-on-error: true

  # ==================================================
  # Package Validation
  # ==================================================
  package-validation:
    name: Package Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate package.json
        run: |
          echo "Validating main package.json..."
          node -e "
            const pkg = JSON.parse(require('fs').readFileSync('package.json', 'utf8'));
            console.log('✅ Package name:', pkg.name);
            console.log('✅ Version:', pkg.version);
            console.log('✅ Scripts available:', Object.keys(pkg.scripts || {}));
          "
      
      - name: Check package dependencies
        run: |
          echo "Checking for common dependency issues..."
          npm ls --depth=0 || echo "Some dependencies might have issues, but continuing..."
        continue-on-error: true

  # ==================================================
  # Security Scan (Basic)
  # ==================================================
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true
      
      - name: Check for hardcoded secrets
        run: |
          echo "Checking for hardcoded secrets..."
          
          if grep -r "sk-.*" --include="*.ts" --include="*.tsx" --include="*.js" --exclude-dir=node_modules . 2>/dev/null; then
            echo "⚠️ Found potential OpenAI API keys"
          fi
          
          if grep -r "supabase.*anon.*key.*=" --include="*.ts" --include="*.tsx" --include="*.js" --exclude-dir=node_modules . 2>/dev/null; then
            echo "⚠️ Found potential hardcoded Supabase keys"
          fi
          
          echo "✅ Basic security check completed"

  # ==================================================
  # Edge Functions Test (if exists)
  # ==================================================
  edge-functions:
    name: Edge Functions Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for Supabase functions
        run: |
          if [ -d "supabase/functions" ]; then
            echo "Found Supabase functions directory"
            ls -la supabase/functions/
            
            # Setup Deno if functions exist
            curl -fsSL https://deno.land/x/install/install.sh | sh
            export PATH="$HOME/.deno/bin:$PATH"
            
            # Check syntax of function files
            cd supabase/functions
            for func in */index.ts; do
              if [ -f "$func" ]; then
                echo "Checking syntax of $func"
                deno check "$func" || echo "Syntax check failed for $func"
              fi
            done
          else
            echo "No Supabase functions directory found, skipping"
          fi
        continue-on-error: true

  # ==================================================
  # Documentation Check (Basic)
  # ==================================================
  docs:
    name: Documentation Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check basic documentation
        run: |
          echo "Checking for basic documentation files..."
          
          [ -f "README.md" ] && echo "✅ README.md exists" || echo "⚠️ README.md missing"
          [ -f "package.json" ] && echo "✅ package.json exists" || echo "❌ package.json missing"
          
          if [ -d "docs" ]; then
            echo "✅ docs directory exists"
            find docs -name "*.md" -type f | head -5
          else
            echo "ℹ️ No docs directory found"
          fi
          
          echo "✅ Documentation check completed"

  # ==================================================
  # Build Artifacts
  # ==================================================
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [build-and-lint]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Production build
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NODE_ENV: production
      
      - name: Verify build artifacts
        run: |
          echo "Checking build output..."
          
          if [ -d ".next" ]; then
            echo "✅ Next.js build successful"
            echo "Build size:"
            du -sh .next/
          else
            echo "❌ No build output found"
            exit 1
          fi

  # ==================================================
  # Success Notification
  # ==================================================
  success:
    name: Success Notification
    runs-on: ubuntu-latest
    needs: [build-and-lint, test, package-validation, security, edge-functions, docs, build-check]
    if: success()
    steps:
      - name: Success summary
        run: |
          echo "🎉 LifeOS CI Pipeline completed successfully!"
          echo ""
          echo "✅ Code quality checks passed"
          echo "✅ Build verification successful"
          echo "✅ Security scan completed"
          echo "✅ Package validation passed"
          echo ""
          echo "Ready for deployment! 🚀"
